name: Auto update

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/data_update.yml'
      - 'script/**'
      - 'game/**'
      - 'repo/**'

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.actor != 'github_actions'

    steps:
      - run: echo "🎉 The job was automatically triggered by ${{ github.actor }}."

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - run: poetry install --no-interaction

      - name: Run script
        run: |
          export LOG_LEVEL=INFO
          poetry run python -m script.run

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "GitHub Actions Update"
          add: "data/*"
          new_branch: data_update_${{github.run_id}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        if: steps.commit.outputs.committed == 'true'
        run: gh pr create --title 'Data Update' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}